#!/bin/bash

apt-get update
apt-get install -y --no-install-recommends \
    ca-certificates \
    gnupg \
    libcurl4 \
    liblzma5  \
    openssl \
    wget
    apt-get clean
  rm -rf /var/lib/apt/lists/*
wget -q https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-debian10-4.4.3.tgz
wget -q https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-debian10-4.4.3.tgz.sig
wget -q https://www.mongodb.org/static/pgp/server-4.4.asc
gpg --import server-4.4.asc
gpg --verify mongodb-linux-x86_64-debian10-4.4.3.tgz.sig mongodb-linux-x86_64-debian10-4.4.3.tgz
tar -zxvf mongodb-linux-x86_64-debian10-4.4.3.tgz
cp ./mongodb-linux-x86_64-debian10-4.4.3/bin/* /usr/local/bin/
mkdir -p /mongo/db
