#!/bin/bash -e

cd "$(dirname "$0")/.."

script/update

docker run \
  --rm \
  -it \
  -v "$(pwd)":/usr/src/book-catalog \
  -v /usr/src/book-catalog/node_modules \
  -e APP_ENV=development \
  -e AUTORUN=true \
  -e DB_PATH=/usr/src/book-catalog/development.sqlite3 \
  -p 6451:3000 \
  book-catalog:dev \
  yarn dev