#!/bin/bash -e

cd "$(dirname "$0")/.."

script/update

docker run \
  --rm \
  -v "$(pwd)":/usr/src/book-catalog \
  -v /usr/src/book-catalog/node_modules \
  -e APP_ENV=test \
  -e DB_PATH=/usr/src/book-catalog/test.sqlite3 \
  book-catalog:dev \
  yarn test