#!/bin/bash -e

cd "$(dirname "$0")/.."

script/update

docker run \
  --rm \
  -v "$(pwd)":/usr/src/audiobook-catalog \
  -v /usr/src/audiobook-catalog/node_modules \
  -e APP_ENV=test \
  -e NODE_ENV=development \
  -e LOG_LEVEL=debug \
  audiobook-catalog:dev \
  npm test
