#!/bin/bash -e

cd "$(dirname "$0")/.."

script/update

docker run \
  --rm \
  -v "$(pwd)":/usr/src/audiobook-catalog \
  -v /usr/src/audiobook-catalog/node_modules \
  -e APP_ENV=test \
  -e DB_PATH=/usr/src/audiobook-catalog/test.sqlite3 \
  audiobook-catalog:dev \
  yarn test